plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation libs.spring.boot.web
    implementation libs.spring.boot.websocket
    implementation libs.spring.boot.mongodb
    implementation libs.spring.boot.redis
    implementation libs.spring.kafka
    implementation libs.firebase.admin
    compileOnly libs.lombok
    annotationProcessor libs.lombok
    testCompileOnly libs.lombok
    testAnnotationProcessor libs.lombok
    testImplementation libs.spring.kafka.test
}
